### ISSUE TITLE
Basecalling raw signal with pyscrap.py

### ISSUE THREAD

**Issue by svkazakov** [nanoporetech/pomoxis#11]
Hello, 

My question is about using pyscrap.py  to run scrappie basecaller. 

Recent comparison of basecallers  \[https://github.com/rrwick/Basecalling-comparison ] said that using `scrappie raw` is much better than `scrappie events`. But as I understood, pyscrap.py can only run basecalling from events, not raw signal.  And how about basecalling from raw signal?

Thanks,
Sergey

**Comment by cjw85** [comment]
The pyscrap binding has not been updated in a while, its on the to do list.

**Comment by cjw85** [comment]
@svkazakov Just by way of an update, we are looking to include a python interface in the next release of scrappie (this will support the raw data basecalling).

**Comment by cjw85** [comment]
Scrappie now includes this functionality.
