### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by jamestwebber** [nanoporetech/pomoxis#12]
Hey, I'm running `make install` on a fresh Ubuntu16 AMI and I've been wrestling with getting various dependencies installed. I don't know if these things can be automated but it would be good to at least put them in the install instructions.

Or maybe I'm not building this correctly, in which case please let me know!

* `libz-dev` to get `zlib.h`
* `libncurses5-dev` for `ncurses.h`
* __[WIP]__ `libhdf5-dev` for `hdf5.h` but it still isn't finding the file, possibly because Ubuntu has a different naming scheme. Working on this one

**Comment by jamestwebber** [comment]
And more:

Fixed the `hdf5.h` issue with judicious application of CFLAGS:
```bash
~/pomoxis$ CFLAGS="-I/usr/include/hdf5/serial" CPPFLAGS="-I/usr/include/hdf5/serial"  make install
```

And then needed to apt-get `libblas-*` (or potentially some subset of that) to get the final header.

**Comment by cjw85** [comment]
Hi @jamestwebber 

Thanks for this reminder! We do aim to list these dependencies (at least for Ubuntu) in the README but in this case it must have slipped. We too have noticed that the include path for hdf on Ubuntu16 needs to be appended.

We'll try to get around to adding a "Ubuntu Dependencies" section to the README, or feel free to send a pull request.
