### ISSUE TITLE
mini_assemble command shows minimap error

### ISSUE THREAD

**Issue by RajneeshSrivastava** [nanoporetech/pomoxis#13]
Hello Admin,
I found pomoxis to be a wonderful tool. 
My query is, while running "mini_assemble" for denovo assembly, it shows following error:
minimap: error: unrecognized arguments: -Sw5 -L100 -m0 -t1
I believe its an issue with minimap vs minimap2. Calling minimap2 might solve the issue. Please let me know how to call it while using mini_assemble

Thanks !

**Comment by cjw85** [comment]
This is fixed in v0.1.5 where we have removed the original version of minimap and cleaned up the options.
