### ISSUE TITLE
dependency on numpy 1.9.0 makes the build process take a long time..

### ISSUE THREAD

**Issue by jamestwebber** [nanoporetech/pomoxis#14]
I'm building an Amazon image using [packer](https://www.packer.io/) and running into issues with my build timing out. As I work on solving this problem, it occurs to me to ask: is there any way to remove this dependency? This version of numpy has to be compiled, and compiling all of numpy takes a long time, so updating whatever code is relying on this would make the process go much faster.

It's probably a good idea anyway, as being tied to a specific outdated version of a package is not a good sign...

If anyone knows what is causing this dependency I can try to write a PR to update the code.

**Comment by cjw85** [comment]
Apologies, the numpy version should no longer be pinned to 1.9.0. It looks like we changed the requirements file but neglected the entry in the Makefile.
