### ISSUE TITLE
Install on mac OSX

### ISSUE THREAD

**Issue by strnadja** [nanoporetech/pomoxis#17]
Encountering the following error when trying to build on OSX:

[ 20%] Building CXX object vendor/spoa/CMakeFiles/spoa.dir/src/alignment_engine.cpp.o
/Users/[...]/pomoxis/submodules/racon/vendor/spoa/src/alignment_engine.cpp:26:9: error: use of undeclared identifier 'exit'
        exit(1);
        ^
/Users/[...]/pomoxis/submodules/racon/vendor/spoa/src/alignment_engine.cpp:32:9: error: use of undeclared identifier 'exit'
        exit(1);
        ^
2 errors generated.
make[3]: *** [vendor/spoa/CMakeFiles/spoa.dir/src/alignment_engine.cpp.o] Error 1
make[2]: *** [vendor/spoa/CMakeFiles/spoa.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [bincache/racon] Error 2

I ought to have all of the dependencies (as listed for Ubuntu) installed. Any ideas appreciated!

Jessica

**Comment by cjw85** [comment]
Hi Jessica

Can you confirm the version of OSX you are using? We updated recently the version of `racon` which we use, and likely have tested only on High Sierra (specifically 10.13.3).

I'm just running through this now, and can't reproduce your error. I've attached the relevant part output from `make install` for you to compare.

[racon_build.log](https://github.com/nanoporetech/pomoxis/files/1896527/racon_build.log)

**Comment by cjw85** [comment]
OK, I can see the error. There has been a fix to this in the racon (https://github.com/rvaser/spoa/commit/2f14820766a7508cd8bd799bb13699c61a5f3b8e) I will update the version of racon we specify.

**Comment by strnadja** [comment]
Looks like that fixed the issue! I'm running El Capitan. Builds with warnings, but no errors.

Thanks!
