### ISSUE TITLE
Error downloading porechop?

### ISSUE THREAD

**Issue by ScarabMonkey** [nanoporetech/pomoxis#20]
When I try to make install I get an error that it can't find Porechop - I have actually already compiled porechop and it is available from this commandline using simply 'porechop' so I'm not sure why pomoxis installer doesn't find it. Pip knows it's already installed - but pomoxis seems to be trying to find it on pypi.org...

```
pip install git+https://github.com/rrwick/Porechop
Collecting git+https://github.com/rrwick/Porechop
  Cloning https://github.com/rrwick/Porechop to /tmp/pip-8a0i93tf-build
  Requirement already satisfied (use --upgrade to upgrade): porechop==0.2.3 from git+https://github.com/rrwick/Porechop in /net/zeta/usr/mbu/software/anaconda3/lib/python3.6/site-packages
```

```
Installed /net/zeta/usr/packages/nanoporetech/pomoxis/venv/lib/python3.6/site-packages/pomoxis-0.1.11-py3.6.egg
Processing dependencies for pomoxis==0.1.11
Searching for Porechop
Reading https://pypi.org/simple/Porechop/
Couldn't find index page for 'Porechop' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for Porechop
error: Could not find suitable distribution for Requirement.parse('Porechop')
make: *** [install] Error 1
```

**Comment by cjw85** [comment]
Hi @ScarabMonkey 

How are you trying to set up pomoxis?

The current Makefile builds a virtual environment and compiles/installs all third party binaries and packages into it. Along the way it should install porechop from its github repo, there's a stage where `pip install -r requirements.txt` is run within the environment.

Your error above appears to have arisen when `python setup.py install` has run without porechop being installed into the environment.

The installation does not depend on, and will ignore, any versions of porechop you have on your existing path.

**Comment by ScarabMonkey** [comment]
I'm following the install guide - just running 'make install'.
The first time I ran this, I hadn't configured a proxy so it failed to download porechop - but after adding the proxy to my environment the make continued on and built loads of stuff (after I added some 'devel' packages)... 

OS: CentOS 7.5 with OpenHPC modules for gnu7
Python: Anaconda3

**Comment by cjw85** [comment]
We don't have much experience with CentOS (we almost exclusively work on Ubuntu, and a bit of macOS), I'll start by trying to reproduce your issue. As I noted above, I suspect its something to do with pip having trouble installing from a github repo.

**Comment by ScarabMonkey** [comment]
I actually have a feeling that the make is not re-running the requirements file after a half-successful previous attempt - is there a way I can force make to re-do the requirements?

**Comment by cjw85** [comment]
The Makefile could definitely do with recovering failed builds better. Try the following (taken from the Makefile):

    sh venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements
    python setup.py install

**Comment by cjw85** [comment]
Hi @ScarabMonkey 
Is this working for you now?

**Comment by avitalsteiman** [comment]
Hi,
I had this problem as well (although working with ubuntu) when i tried to run python setup.py install after pulling down a change ([(https://github.com/nanoporetech/pomoxis/issues/29] ). 
I tried running the commands you suggested above:
`sh venv/bin/activate`
`pip install --upgrade pip`
`pip install -r requirements`
 and received the following error:

>  Could not find a version that satisfies the requirement Porechop (from -r pomoxis.egg-info/requires.txt (line 14)) (from versions: )
No matching distribution found for Porechop (from -r pomoxis.egg-info/requires.txt (line 14))

Any ideas? 
Thanks
