### ISSUE TITLE
Mini_assemble issue in line 188 specifying # threads

### ISSUE THREAD

**Issue by ccbruels** [nanoporetech/pomoxis#21]
Line 188 of /apps/nanopore/pomoxis/0.1.11/bin/mini_assemble is currently:
    minimap2 -t${THREADS} ${SCAFFOLD} ${SHUFREADS} > ${READS2TIGS}

Shouldn't it be: 
minimap2 -t ${THREADS} ${SCAFFOLD} ${SHUFREADS} > ${READS2TIGS}​

Without the space between -t and ${THREADS}, when I specify a number of threads, it's interpreted as -t16 rather than -t 16, and causes minimap2 to not work properly, and racon fails during the first round consensus...

**Comment by cjw85** [comment]
I've not seen the lack of a space should cause an issue before. Can you provide the full command you are running and the output of mini_assemble?
