### ISSUE TITLE
minimap2 doesn't work

### ISSUE THREAD

**Issue by avitalsteiman** [nanoporetech/pomoxis#26]
Hi,
I installed pomaxis and am running mini_align in the pomaxis setting, but for some reason it does not recognize the minimap2 command.

I run:
>mini_align -i filtered.fq -r ~/refs/lambda_ref.fasta -P -p lambda -t 14

 I get this error:
/home/biomesh/git/pomoxis/venv/bin/mini_align: line 95: minimap2: command not found

Also, if i try to run minimap2 directly using the command:
>../../../git/pomoxis/submodules/minimap2-2.14/minimap2  -x map-ont  -t  14 -a  /home/biomesh/refs/lambda_ref.fasta.mmi filtered.fq
I get :  Segmentation fault (core dumped)

I noticed that minimap2 was already downloaded but not installed by another user on the computer i'm running on, but even after i erased the file it doesn't work.  "Minimap" is installed though. Could this be part of the problem.

Thanks,
Avital

**Comment by cjw85** [comment]
Hi @avitalsteiman,

From your second error it appears the installation successfully compiled `minimap2`, whilst the first error suggests the program was not move correctly to a location where `mini_align` can find it: `minimap2` should be present under `/home/biomesh/git/pomoxis/venv/bin/`. Can you confirm the contents of this directory? It you have a log file from when pomoxis was installed this would be useful; if not perhaps try a clean install with e.g.:

    git clone --recursive https://github.com/nanoporetech/pomoxis pomoxis_clean
    cd pomoxis_clean
    make install &> install.log

and attach the file install.log to this issue.

For the Segmentation fault in the second error, can you confirm that the error does not occur for your inputs with a `minimap2` compiled independently of pomoxis?

**Comment by avitalsteiman** [comment]
Thanks for your response.

I checked and minimap2 was missing from "/home/biomesh/git/pomoxis/venv/bin/"
I re-installed pomoxis using the commands you included.
The install.log is attached.
I then re-ran the mini_align command:
`mini_align -i filtered.fq -r ~/refs/lambda_ref.fasta -P -p lambda -t 14`
and received this output on the screen:

> -P option is deprecated
> Found minimap files.

and it created the lambda.bam and lambda.bai file as well as test.sam
however the test.sam file was empty and when I tried viewing the bam file on the tablet viewer i received an error that the indexed file was empty (the .bami file had 16bytes)

I then ran the minimap2 independently:
`minimap2  -x map-ont -t 14 -a /home/biomesh/refs/lambda_ref.fasta.mmi filtered.fq`
and received the same segmentation fault:

Any ideas? Thanks again!


[install.log](https://github.com/nanoporetech/pomoxis/files/2755070/install.log)

**Comment by cjw85** [comment]
Aside from the python3.7 errors (see https://github.com/nanoporetech/pomoxis/issues/25, python3.7 is unsupported, the next release will make this more clear), there does not appear to be anything untoward going on during installation.

You say `mini_align` created a `test.sam` file, however this is not a file that would be created given the command you say you have run. I suspect the minimap index (`lambda_ref.fasta.mmi`) is somehow invalid, causing the segmentation fault. Could you attach your `~/refs/lambda_ref.fasta`?

**Comment by avitalsteiman** [comment]
Hi,
I updated my post at the same time that you responded....
Your assessment was correct.
I noticed that in fact there was a problem with the originl
lambda_ref.fasta file and the .mmi file.
After I replaced the lambda_ref.fasta file and removed the
lambda_ref.fasta.mmi file the mini_align command worked.

Thanks for your help.
I appreciate your quick response.
Avital

**Comment by cjw85** [comment]
No problem, happy to help.
