### ISSUE TITLE
Bulk .fast5 datasets

### ISSUE THREAD

**Issue by svkazakov** [nanoporetech/pomoxis#3]
Hello,

I want to test read_until_filter.py from pomoxis.apps, but I need a bulk .fast5 file to do this. The only bulk .fast5 file I can find was elec3_example.fast5 from fast5_research test data, but it seems to be truncated.

So, 
1. Can you suggest a public dataset with bulk fast5 files to test read_until_filter.py on it?
2. Can a bulk .fast5 file be constructed from a set of usual .fast5 files?  

<br/><br/>

Thanks for an advice,
Sergey

**Comment by cjw85** [comment]
Hi @svkazakov,

Thank you for your interest in read until. A bulk .fast5 file cannot be constructed from .fast5 containing read data; the bulk file contains additional regions of signal which the read .fast5 files omit.

Oxford Nanopore Technologies' has not currently made public any bulk .fast5 files; it may be something we do in future. They can be generated by users by following instructions given in the Nanopore Community.

I'll leave this Issue open in case any passing users are willing to share such a file.
