### ISSUE TITLE
pomoxis assess assembly `-T` parameter without `-b` gives an error.

### ISSUE THREAD

**Issue by kishwarshafin** [nanoporetech/pomoxis#32]
Hello,

I've been using the assess assembly module, and it's really helpful. But I am having an issue running it with `-T` and without a bed file parameter. My intended use is: <br>
```bash
assess_assembly \
-i <input_fasta> \
-r <ref_fasta> \ 
-t <threads> \
-p <output_prefix> \
-T 
```

In this setup, if you look through the script, the mini_align under "trim" condition is missing `-m` parameter which ends up not generating an `MD` tag in the alignment and `ref_seqs_from_bam` throws a ValueError saying `no MD tag found.` If I enable `-C` or edit the script to have `-m` in mini_align that fixes the problem, is my intended use not correct? I generated a bed file with all the segments of primary alignment, and it gives the same result. So, there may need to be a fix?

**Comment by cjw85** [comment]
Hi @kishwarshafin,

This looks like it may be an unhandled case. This week is naturally a busy week for us with [London Calling](https://londoncallingconf.co.uk/lc19) next week. We will have a look at this at the first opportunity.

**Comment by kishwarshafin** [comment]
Good to know. I understand, I am also using this for London Calling :-). No worries, I have a fix. Just wanted to be sure that this is an unhandled case not an unintended use of the analysis pipeline. Thanks for the quick reply. 👍

**Comment by cjw85** [comment]
This should now be available in pypi and conda and well as the source on github.

**Comment by kishwarshafin** [comment]
Thank you so much!

**Comment by cjw85** [comment]
No problem, thanks.
