### ISSUE TITLE
pomoxis installation

### ISSUE THREAD

**Issue by xinghai999** [nanoporetech/pomoxis#34]
Hi,
I am getting the following error related to install pomoxis though conda.
![2019-06-18 (2)](https://user-images.githubusercontent.com/51962798/59696993-ac11cd00-921f-11e9-98cd-f2d7c82b8167.png)
Any suggestions how to resolve?

**Comment by cjw85** [comment]
Hi,

Pomoxis is now available through the [bioconda](https://bioconda.github.io/recipes/pomoxis/README.html) channel. We will update the README to reflect this fact.

**Comment by xinghai999** [comment]
Thanks a lot!

**Comment by cjw85** [comment]
README and docs have been updated.
