### ISSUE TITLE
[bug] Running catalogue_errors then get 'ValueError: MD tag not present'

### ISSUE THREAD

**Issue by yipukangda** [nanoporetech/pomoxis#43]
I run catalogue_errors program with cmd:

```
catalogue_errors -t 20 -o variant ont.bam
```

And get an error message shows:

```
ValueError: MD tag not present
```

pomoxis version 0.3.4

**Comment by cjw85** [comment]
The `catalogue_errors` program requires the MD tag to be present in the input bam file, this can be generated using `samtools calmd`: http://www.htslib.org/doc/samtools-calmd.html

**Comment by yipukangda** [comment]
> The `catalogue_errors` program requires the MD tag to be present in the input bam file, this can be generated using `samtools calmd`: http://www.htslib.org/doc/samtools-calmd.html

it works, Thanks for helping.
