### ISSUE TITLE
Assess_assembly documentation

### ISSUE THREAD

**Issue by mpalmada** [nanoporetech/pomoxis#46]
Hi!

I would like to know more what does each output of assess_assembly mean, and how could I get an overall assembly accuracy value to compare assemblies before and after polishing steps. 

I would also thank if you tell me if you regularly use ONT reads that were used for the assembly as the mapping reads to evaluate it.

Thanks a lot! 

Marc

**Comment by ftostevin-ont** [comment]
Hi Marc,
Assuming default options to assess_assembly, the outputs are:
- `assm.bam{,.bai}` - chunked assembly aligned to the reference
- `assm_stats.txt` - alignment and error statistics for each chunk of the alignment
- `assm_summ.txt` - summary of alignment statistics, the error rates and associated Q-scores for the assembly as a whole and for each reference contig. `mean` is the length-weighted mean over chunks (thus the overall value for the whole assembly), `qX` are unweighted values for different percentiles of the chunk population. For more details of the different metrics see [here](https://github.com/nanoporetech/pomoxis/issues/30).
- The terminal output is the same as the whole-assembly section from `assm_summ.txt`

For assessing overall assembly accuracy, you will probably want to use whole-assembly values from `assm_summ.txt`, either the `mean` or `qX` depending on your usecase.

`assess_assembly` currently only supports evaluating assemblies against a known reference, not against reads.

**Comment by mpalmada** [comment]
Hi!

Thanks for responding! Now the results are clear to me! About the second question, I wondered if it is "fair" or "common" to use the reads I used to do the reference as the ones to evaluate it?

Thanks!

Marc

**Comment by ftostevin-ont** [comment]
This issue tracker is intended for software issues and is not the right place for discussing what is "common" practice.
`assess_assembly` attempts to quantify base-level accuracy (not contiguity, SVs, etc), so it would not be appropriate to use it to assess an assembly against reads (whether used for that assembly or not), nor for identifying misassemblies from alignments of reads.
