### ISSUE TITLE
 medaka requires pomoxis in order to run :: mini_align name conflict

### ISSUE THREAD

**Issue by EricDeveaud** [nanoporetech/pomoxis#49]
same problem here: https://github.com/nanoporetech/medaka/issues/331

 both pomoxis and medaka provides a mini_align script

currently they are in sync (no diffs)

may I suggest that either one of the distribution drops the min_align script, or mini_align name will be adapted in order to avoid name_conflicts

regards

Eric

**Comment by cjw85** [comment]
Closing as duplicate.
