### ISSUE TITLE
porechop installation fails

### ISSUE THREAD

**Issue by jstraubhr** [nanoporetech/pomoxis#50]
python version 3.6.13
installation with pip in conda environment: pip install git+https://github.com/rrwick/Porechop
error messages:
Building wheels for collected packages: porechop
  Building wheel for porechop (setup.py) ... error
...
g++: error: unrecognized command line option ‘-std=c++14’

Thank you

**Comment by ftostevin-ont** [comment]
v0.3.15 pypi release no longer has an install-time dependency on porechop.
By the way, if you are working in a conda there is a conda package available on bioconda: https://bioconda.github.io/recipes/pomoxis/README.html
