### ISSUE TITLE
Cannot open include file: 'dirent.h'

### ISSUE THREAD

**Issue by barak2** [nanoporetech/pomoxis#7]
I am trying to install this package however i ran into this:
pomoxis\pyscrap\pyscrap.c(4): fatal error C1083: Cannot open include file: 'dirent.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

how can i finish the installation? thanks

**Comment by cjw85** [comment]
Hi @barak2 

Pomoxis is a research offering. As such we do not actively target and test on all platforms (though we do try to develop such things in mind where possibly). Several of the binary tools bundled with pomoxis also have limited cross-platform support. It is therefore unlikely that we will support pomoxis on windows in the near future.

Apologies; we will make this more clear in the README.
