### ISSUE TITLE
where should i clone pomoxis?

### ISSUE THREAD

**Issue by barak2** [nanoporetech/pomoxis#8]
I have created python3 environment and activated it.
I entered its path and tried to clone and install pomoxis:

~/environments/Python3_env/pomoxis
and got this error:

test -d venv || virtualenv venv --python=python3
/bin/sh: 1: virtualenv: not found
Makefile:54: recipe for target 'venv/bin/activate' failed
make: *** [venv/bin/activate] Error 127

I guess i have cloned it to the wrong place, but i didn't where did you want it to be.
thanks.

**Comment by cjw85** [comment]
Hi @barak2 
The above looks like you are attempting to run the Makefile from within a virtual environment. This isn't necessary as running `make` will create a fresh environment (and is likely the source of the error: virtualenv the program is not available within the environment you have created beforehand).

Could you please try following the instructions provided [here](https://github.com/nanoporetech/pomoxis#build), outside of any special environment?

**Comment by barak2** [comment]
even outside an environment it still sends me this error.
